name: test
on: [ push, pull_request ]
env:
  CURL: "curl -fsSkL --retry 9 --retry-delay 9"
  GHRAW: "https://raw.githubusercontent.com"
  BUILD_MAGIT_LIBGIT: "false"
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        emacs_version:
        - 25.1
        # 25.2 is identical to 25.3 except for a critical security bug in
        # enriched text mode (see Emacs Bug#28350).
        - 25.3
        - 26.1   # Debian is on this version.
        - 26.3
        - 27.1
        - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - name: Install
      run: |
        $CURL -O ${GHRAW}/magnars/dash.el/master/dash.el
        $CURL -O ${GHRAW}/magit/transient/master/lisp/transient.el
        $CURL -O ${GHRAW}/magit/with-editor/master/with-editor.el
        emacs -Q --batch -L . -f batch-byte-compile dash.el transient.el with-editor.el
        emacs --version
        git config --global user.name "A U Thor"
        git config --global user.email a.u.thor@example.com
        git tag 0
    - name: Compile
      run: |
        make lisp DASH_DIR=$PWD
    - name: Test
      run: |
        make test DASH_DIR=$PWD
